GAME_RES=(500, 800)
GAME_FPS=60

BG_IMAGE="assets/background.jpg"
SHIP_IMAGE="assets/ship.png"
METEOR_IMAGE="assets/Meteor1.png"

FONT_TYPE="comicsans"
FONT_SIZE=50
FONT_COLOR=(255, 255, 255)

BG_BASE_POS=(0,0)

SHIP_SPEED=5
SHIP_BASE_COORD=(250, 720)

METEOR_BASE_COUNT=4
METEOR_COUNT_INCREMENT=4
METEOR_BASE_SPEED=1
METEOR_SPEED_INCREMENT=1

